### ISSUE TITLE
How does sast integrate new code inspection tools?

### ISSUE THREAD

**Issue by niuzhi** [ShiftLeftSecurity/sast-scan#140]
How does sast integrate new code inspection tools? How to add new custom inspection rules? For example, add the check of the infer tool.

**Comment by prabhu** [comment]
Hi @niuzhi
Do you have a specific tool or rule in mind? Adding a tool currently takes anywhere from 2 days to 2 weeks depending on the work required to convert the report to sarif format and fix false positives. Happy to document the steps involved while working on a new tool.

**Comment by niuzhi** [comment]
hi @prabhu
Infer and so on

**Comment by prabhu** [comment]
I remember seeing infer sometime back. Can it perform any security checks or pure linting? I can see [Quandary](https://fbinfer.com/docs/experimental-checkers/#quandary) but not sure how good it is. Do you have any example repos that show these in action?
