### ISSUE TITLE
detecting secret in a file that doesn't exist

### ISSUE THREAD

**Issue by jooh-lee** [ShiftLeftSecurity/sast-scan#149]
This is a weird one and not sure how to even debug. In our private frontend mono-repo the scan is detecting a plaintext secret in the following file `src/components/table/responsive-table.tsx` however in the actual codebase the file doesn't actually exist. The closest is `src/component/tables/table.tsx`. I printed the contents of `src/components` and there is no `table` folder in there in the ci build project. Has this ever been encountered?

**Comment by prabhu** [comment]
Hi @jooh-lee 

Scan can detect secrets even in files that were deleted from git but still available in the form of commits and git history. Take the commit hash reported and search for that commit. In case of github you can use the url of the form repo/commit/hash

**Comment by prabhu** [comment]
@jooh-lee did it help?

**Comment by jooh-lee** [comment]
hi, turns out its a problem with codebuild's git clone depth setting. If you set it outside the pre-determined 1,5,25... it just pulls the full history. It does allow you to set other number through terraform, but it doesnt respect it. I had it set for clone depth of 2

**Comment by prabhu** [comment]
Great find! Btw, will you be kind enough to share a working configuration for codebuild and codepipeline? I will add it to the docs and credit you!
