### ISSUE TITLE
Support for baseline

### ISSUE THREAD

**Issue by prabhu** [ShiftLeftSecurity/sast-scan#155]
Every invocation of scan is currently a fresh invocation resulting in a full scan. For teams with known technical debt this is resulting in many findings per scan and is affecting the ability to identify new issues from a particular branch or PR. With a remote server and API access it is possible to implement features to compare findings across invocations. It is also possible to use GitHub Code scanning to filter new issues from recurring ones. However, a native baselining feature that uses git and doesn't rely on a remote server is nice.

While SARIF and ShiftLeft findings format has support for tracking baseline state, the contents are quite verbose and might include sensitive information. We need a new format for defining baseline state by making use of the `calculate_line_hash` method we already have. New parameter could be added to create baseline states which could be persisted in the repo or in an external storage such as CI cache.

https://github.com/ShiftLeftSecurity/scan-action/issues/16

**Comment by gitnachogo** [comment]
Definitely, one of the things that makes people trust it the most is not to send any data to an external server, so I agree with the idea of using CI cache or some other ways too.
I think I could be up to develop this feature next month or the following 👍

**Comment by gitnachogo** [comment]
I'd like to start the development of this feature.
To start, I think that we could take the `.findings.json` to use the `internal_id` attribute of each finding. So the user should pass the `.findings.json` file that he wants as a baseline, and then we could compare and mark the recurring issues using the attribute `first_found`.
