### ISSUE TITLE
Any plans to support c#?

### ISSUE THREAD

**Issue by andrecarlucci** [ShiftLeftSecurity/sast-scan#188]

**Comment by prabhu** [comment]
Hi @andrecarlucci 

c# is supported in our commercial product. Below is a sample repo and link to the docs:

https://github.com/ShiftLeftSecurity/shiftleft-csharp-example
https://docs.shiftleft.io/ngsast/analyzing-applications/c-sharp

With scan, I couldn't find a suitable opensource alternative for SAST. Dependency and license scan however are supported for .Net core projects. If you come across any SAST tools, please let us know and we will be happy to evaluate.

**Comment by andrecarlucci** [comment]
Awesome, thanks for the info :)
