### ISSUE TITLE
VS Code Extension "unable to create context store: $HOME is not defined"

### ISSUE THREAD

**Issue by troyfontaine** [ShiftLeftSecurity/sast-scan#196]
VS Code Version 1.48.2
Host OS: MacOS 10.14.6
Security Scan: 1.2.0

Upon installing the extension, the security scan ran automatically and threw the error "unable to create context store: $HOME is not defined" in the Output pane of VS Code.  And running it manually also triggers the same error.

**Comment by prabhu** [comment]
Hi @troyfontaine Are you confident it was sast-scan that threw the output? scan uses a separate output channel for the vs code extension. Also was it reproducible after reloading the window?

**Comment by troyfontaine** [comment]
Hi @prabhu I am confident it is sast-scan generating it-it occurs every time I try to run a scan from the UI in VS Code via the extension.  Reloading, uninstalling and re-installing it continues to occur.

![image](https://user-images.githubusercontent.com/11366027/92622128-53967780-f28a-11ea-95f4-8241c16ec52b.png)

The scanner UI will just sit there as if hung on the error:
![image](https://user-images.githubusercontent.com/11366027/92622201-68730b00-f28a-11ea-8572-cdfeb51e820f.png)

**Comment by prabhu** [comment]
Interesting! Is docker desktop for mac running btw? Are you able to run scan via the cli and then see the reports with the extension? You can open the .sarif files generated in reports directory and the extension should automatically display it.

**Comment by troyfontaine** [comment]
@prabhu I've been able to run scans using the example commands without issues.  The .sarif file is not automatically previewed when I double click on it in the VS-Code window's file list.

**Comment by prabhu** [comment]
ok will take a look. Have to find a mac since I have moved to linux and windows :(

**Comment by prabhu** [comment]
The extension is working fine for me on a mac. I even asked another colleague to test. Are there any errors in the developer tools on vs code?

**Comment by troyfontaine** [comment]
> The extension is working fine for me on a mac. I even asked another colleague to test. Are there any errors in the developer tools on vs code?

I'll check this morning.  I am now noticing a pop up in the lower right corner of VS Code asking if Docker for Mac is installed.  I am using Docker for Mac edge if that plays at all into things-but I will check the developer tools and look at reinstalling VS Code.

**Comment by troyfontaine** [comment]
Hi @prabhu looks like it was specifically that I was using Docker for Mac edge.  Uninstalling and installing Stable the VS Code Plugin works fine.

**Comment by prabhu** [comment]
Thanks @troyfontaine. I will try to reproduce this docker edge and iterm and get back to you.

**Comment by prabhu** [comment]
Hi @troyfontaine 

Can you try the extension from the below link to see if it works on both docker edge and stable version on mac?

https://github.com/ShiftLeftSecurity/shiftleft-scan-vscode/suites/1182490143/artifacts/17312616

**Comment by troyfontaine** [comment]
@prabhu that did the trick, it is now running and the .sarif file is viewable in VSCode.  Thanks!

**Comment by prabhu** [comment]
Cool. We will release the new extension in a few minutes. As an added bonus, it also comes with a new light color theme.
