### ISSUE TITLE
Improve comments template

### ISSUE THREAD

**Issue by gitnachogo** [ShiftLeftSecurity/sast-scan#199]
Hi!
As we have been talking in [#support in Discord](https://discord.com/channels/739799745685618730/739799887272607845/755406960089759795), I think it could be nice to dispose of some helpful variables like `recommendation` or `summary`, but just containing the info of some common variables that people could want to retrieve for customizing the template.
For example: `jobId = (f"{gitlab_context.get('jobId'})`
I'll send the PR as soon as I develop it!
And thanks for the help!

**Comment by prabhu** [comment]
Thank you
