### ISSUE TITLE
Use requirements.txt for Python depscan

### ISSUE THREAD

**Issue by Dreamsorcerer** [ShiftLeftSecurity/sast-scan#205]
Is it possible to configure the scan to use requirements.txt instead of the system-installed packages?

We have the packages installed in a docker image, but this scan then highlights problems with packages installed on the host system, not what is actually used by the application in production.

**Comment by prabhu** [comment]
Hi @Dreamsorcerer,

depscan should only use the packages specified in requirements.txt. Will you be able to share the results so that I can investigate? Even email is best: prabhu at shiftleft.io

**Comment by prabhu** [comment]
Thank you for your time today. This turned out to be a true positive with one of the sub-project requiring the vulnerable version.
