### ISSUE TITLE
Does Android kotlin project scanning work properly?

### ISSUE THREAD

**Issue by donnie-jp** [ShiftLeftSecurity/sast-scan#221]
When I scan our project through GitHub Actions scanner I see the following in the scan output:

```
[02:32:26] INFO     Scanning /github/workspace using plugins ['credscan', 'kotlin', 'depscan']                                              
           INFO     ANDROID_SDK_ROOT or ANDROID_HOME should be set for automatically building android projects                              
                         SAST Scan Summary                          
╔════════════════════════╤══════════╤══════╤════════╤═════╤════════╗
║ Tool                   │ Critical │ High │ Medium │ Low │ Status ║
╟────────────────────────┼──────────┼──────┼────────┼─────┼
║ Kotlin Static Analysis │        0 │    0 │      0 │   0 │   ✅   ║
║ Kotlin Security Audit  │        0 │    0 │      0 │   0 │   ✅   ║
╚════════════════════════╧══════════╧══════╧════════╧═════╧════════╝
```

It doesn't look like it scanned.
Is Android kotlin supported?

Thanks

**Comment by prabhu** [comment]
Hi @donnie-jp,

Yes, Android with Kotlin is supported. However, scan requires the project to be compiled which can be either manual or automatic

- Manual: Run the gradle commands before the scan step. Example workflow here - https://github.com/prabhu/AndroGoat/blob/master/.github/workflows/shiftleft-analysis.yml
- Automatic: Set the environment variable ANDROID_SDK_ROOT based on GitHub action documentation

I think it might be the below value but please confirm.

```
export ANDROID_SDK_ROOT=${HOME}/Library/Android/sdk
```

**Comment by donnie-jp** [comment]
Thanks. I had to manually compile - just adding the ANDROID_SDK_ROOT didn't work. Probably due to the project structure.

Here's my results:
https://github.com/rakutentech/android-remote-config/pull/43/checks?check_run_id=1319991368

**Comment by prabhu** [comment]
This looks great! Thank you for supporting scan! Please feel free to drop by to our discord channel for any questions or comments.
