### ISSUE TITLE
include depscan results in PR annotation

### ISSUE THREAD

**Issue by stevesea** [ShiftLeftSecurity/sast-scan#222]
depscan doesn't cause the build to break (see https://github.com/ShiftLeftSecurity/sast-scan/issues/136) (reasoning there seems fine), but the depscan results also aren't included in the MR decoration (at least in gitlab).

for example, I've got a nodejs project with the following depscan results: 

```
Dependency Scan Summary (nodejs)
╔═════════════╤═══════╤════════╗
║ Severity    │ Count │ Status ║
╟─────────────┼───────┼────────╢
║ UNSPECIFIED │     0 │ ✅     ║
║ LOW         │     6 │ ✅     ║
║ MEDIUM      │     6 │ ✅     ║
║ HIGH        │    19 │ ❌     ║
║ CRITICAL    │     2 │ ❌     ║
╚═════════════╧═══════╧════════╝
```
and sast scan summary:

```
                                                                                                                     
                           SAST Scan Summary                            
╔════════════════════════════╤══════════╤══════╤════════╤═════╤════════╗
║ Tool                       │ Critical │ High │ Medium │ Low │ Status ║
╟────────────────────────────┼──────────┼──────┼────────┼─────┼────────╢
║ JavaScript Source Analyzer │        0 │    0 │      0 │   2 │   ✅   ║
╚════════════════════════════╧══════════╧══════╧════════╧═════╧════════╝
```

and the MR is decorated with
<img width="651" alt="Screen Shot 2020-10-22 at 6 34 12 PM" src="https://user-images.githubusercontent.com/10570015/96943385-2fd36d80-1495-11eb-83f0-f20af2af6555.png">

Due to no depscan MR decoration and a successful pipeline, the user & reviewer has to be relied upon to go investigate the output of the sast-scan job to find whether or not there are failures.

**Comment by prabhu** [comment]
@stevesea Working hard towards this feature. Need some more time :( Only recently we rolled out usage detection for depscan where the results will indicate if the vulnerable package is used in the application or not. Are you able to see this information out of curiosity?

The build breaker logic would have new keys for depscan as shown below:

```
{
  "depscan": {
      "max_critical": 0,
      "max_required_critical": 0,
      "max_optional_critical": 0
   }
}
```

`max_required_critical` - This would indicate maximum critical vulnerabilities allowed in required packages (Packages that are used)
`max_optional_critical` - Optional packages such as dev or test packages.

**Comment by gitnachogo** [comment]
Hi @prabhu ! I'm testing this build_breaker_rule for depscan and it doesn't seem to work.
```
"build_break_rules": {
    "default": {
      "max_critical": 5,
      "max_high": 10,
      "max_medium": 15
    },
    "depscan": {
      "max_critical": 10,
      "max_required_critical": 1,
      "max_optional_critical": 20
    }
  }
```
Output (2 used critical):
```
 ╔════════════════════════╤══════════╤══════╤════════╤═════╤════════╗
 ║ Tool                   │ Critical │ High │ Medium │ Low │ Status ║
 ╟────────────────────────┼──────────┼──────┼────────┼─────┼────────╢
 ║ Dependency Scan (java) │       24 │   23 │      7 │   0 │   ✅   ║
 ║ Class File Analyzer    │        9 │   98 │      4 │   0 │   ❌   ║
 ║ Java Source Analyzer   │        0 │    0 │      0 │   0 │   ✅   ║
 ╚════════════════════════╧══════════╧══════╧════════╧═════╧════════╝
```
