### ISSUE TITLE
Bundle cyclonedx maven plugins

### ISSUE THREAD

**Issue by prabhu** [ShiftLeftSecurity/sast-scan#229]
In organizations using a private maven artifactory, `com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.1` is not getting downloaded. This is because this particular library is published in jitpack.io where as people tend to use just maven central by default.

```
[ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.1.0:makeAggregateBom (default-cli) on project orderchangenotif: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:2.1.0:makeAggregateBom failed: Plugin org.cyclonedx:cyclonedx-maven-plugin:2.1.0 or one of its dependencies could not be resolved: Failure to find com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.1 in  was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

The above error will not show up unless the user explicitly runs the below maven command. The symptom is the entire column `Used?` appearing as `N/A` for Java with maven projects.

```
mvn org.cyclonedx:cyclonedx-maven-plugin:2.1.0:makeAggregateBom
```

[ ] Scan image could bundle all the required jars and configure mvn used by cdxgen to use a local plugin directory if available.
[ ] cdxgen could also do a better job at logging all maven errors correctly

**Comment by prabhu** [comment]
cdxgen 2.0.16 would log maven errors when env variables SCAN_DEBUG_MODE is set to debug or when NODE_ENV is ci.

**Comment by gitnachogo** [comment]
I've found two ideas to load a plugin.

1. To install it to the local repo, so the following command could be used just before the makeAggregateBom:
```
mvn install:install-file -Dfile=your-artifact-1.0.jar \
 [-DpomFile=your-pom.xml] \ [-Dsources=src.jar] \
 [-Djavadoc=apidocs.jar] \
 [-DgroupId=org.some.group] \
 [-DartifactId=your-artifact] \
 [-Dversion=1.0] \
 [-Dpackaging=jar] \
 [-Dclassifier=sources] \
 [-DgeneratePom=true] \
 [-DcreateChecksum=true]
```
More info here: https://maven.apache.org/plugins/maven-install-plugin/usage.html

2. To get the dependency from the repository:
`mvn dependency:get -DrepoUrl=https://jitpack.io
-Dartifact=com.github.everit-org.json-schema:org.everit.json.schema:1.12.1`

**Comment by prabhu** [comment]
@gitnachogo Thank you for sharing these two commands. Idea #2 sounds interesting. Will you be able to send a PR by adding that command here? https://github.com/AppThreat/cdxgen/blob/master/index.js#L393

```
result = spawnSync(
        MVN_CMD,
        ["dependency:get", "-DrepoUrl=https://jitpack.io", "-Dartifact=com.github.everit-org.json-schema:org.everit.json.schema:1.12.1"],
        { cwd: basePath, encoding: "utf-8" }
      );
```

Please run a quick test to make sure it doesn't break anything.
