### ISSUE TITLE
whitelist acceptable vulnerabilities

### ISSUE THREAD

**Issue by noelnuguid** [ShiftLeftSecurity/sast-scan#257]
Is there a way to whitelist vulnerabilities (we have an internal process that certifies that the team is willing to accept the risks of these vulnerabilities) so that scans will still pass without remediating the issues found by the scanner?

I need to implement this in nodjs, python, depscan and credscan.

**Comment by prabhu** [comment]
Hi @noelnuguid 

There is a suppression feature that makes use of a comment tag

https://slscan.io/en/latest/getting-started/#suppression

It may be possible to have a local .sastscanrc file with a big list of ignored rules based on this list https://github.com/ShiftLeftSecurity/sast-scan/blob/master/lib/config.py#L785

Let me know if this could work. If not, we can definitely revisit and improve the ignore functionality.

**Comment by prabhu** [comment]
@noelnuguid Was the information I had shared useful?

**Comment by noelnuguid** [comment]
Sorry for the delay. but yes it was useful.
