### ISSUE TITLE
Output reports directory saved with root permission

### ISSUE THREAD

**Issue by niltongouveajr** [ShiftLeftSecurity/sast-scan#279]
Hi!

Is there a way to generate reports as a non-root user using Docker? I am testing ShiftLeft sast in a pipeline on Azure and the reports directory with root permission is causing problems. The same happened with Jenkins. The tools are unable to remove / clean the workspace from the second run:

`## [error] One or more errors occurred. (One or more errors occurred. (Access to the path '/srv/azure-devops/work/2/a/CodeAnalysisLogs/depscan-report-nodejs.json' is denied.)) (One or more errors occurred. (Access to the path '/srv/azure-devops/work/2/a/CodeAnalysisLogs/scan-full-report.json' is denied.)) (Access to the path '/ srv / azure-devops / work / 2 / a /CodeAnalysisLogs/depscan-report-nodejs.json 'is denied.) (Access to the path' /srv/azure-devops/work/2/a/CodeAnalysisLogs/scan-full-report.json 'is denied.)`

Command used:

`$ docker run --rm -e "SCAN_DEBUG_MODE=debug" -e "WORKSPACE=${PWD}" -v $PWD:/app shiftleft/sast-scan:latest scan --build`

`$ ls -la | grep reports`                                                                                            
`drwxr-xr-x   2 root    root          4096 fev 25 16:49 reports`

**Comment by prabhu** [comment]
Hi @niltongouveajr 

docker run command supports --user

`--user 1000:1000`. Please make this match the jenkins user

https://docs.docker.com/engine/reference/commandline/run/

**Comment by niltongouveajr** [comment]
I tried this. But it seems to me that the tools inside the container need to run as root ...

docker run --rm -e "SCAN_DEBUG_MODE=debug" -e "WORKSPACE=${PWD}" -v $PWD:/app -u $(id -u):$(id -g) shiftleft/sast-scan:latest scan --build

███████╗ ██████╗ █████╗ ███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║
███████╗██║     ███████║██╔██╗ ██║
╚════██║██║     ██╔══██║██║╚██╗██║
███████║╚██████╗██║  ██║██║ ╚████║
╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝

[22:13:11] INFO     Scanning /app using plugins ['credscan', 'nodejs', 'yaml', 'depscan']                                                   
           DEBUG    ⚡︎ Executing auto-build "npm install"                                                                                   
Building with auto-build ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% -:--:--[22:13:13] DEBUG    ⚡︎ Executing auto-build "npm run build"                                                                                 
Building with auto-build ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% -:--:--[22:13:14] DEBUG    ⚡︎ Executing credscan "gitleaks --config=/usr/local/src/lib/../credscan-config.toml --depth=5 --repo-path=/app --redact 
                    --timeout=2m --report=/app/reports/credscan-report.json --report-format=json"                                           
[22:13:14] DEBUG    njsscan is no longer bundled with scan. Please use shiftleft/scan-oss container image if this tool is required.         
[22:13:14] DEBUG    ⚡︎ Executing depscan "/usr/local/bin/depscan --no-banner --suggest --src /app --report_file                             
                    /app/reports/depscan-report.json"                                                                                       
           DEBUG    Know any decent open-source SAST tool for JavaScript? It should use AST and CFG and not just regex or grep. Please let  
                    us know 👍                                                                                                              
           DEBUG    Please feel free to try ShiftLeft NG SAST. To enable visit https://www.shiftleft.io/register to signup and pass the     
                    tokens as environment variables!                                                                                        
Scanning with credscan ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% -:--:--Traceback (most recent call last):
  File "/usr/local/bin/depscan", line 5, in <module>
    from depscan.cli import main
  File "/usr/local/lib/python3.8/site-packages/depscan/cli.py", line 9, in <module>
    from vdb.lib import config as config
  File "/usr/local/lib/python3.8/site-packages/vdb/lib/config.py", line 21, in <module>
    os.makedirs(data_dir)
  File "/usr/lib64/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
Scanning with depscan ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% -:--:--Traceback (most recent call last):
  File "/usr/local/src/scan", line 794, in <module>
    main()
  File "/usr/local/src/scan", line 753, in main
    findings_file = inspect.convert_to_findings(
  File "/usr/local/src/lib/inspect.py", line 285, in convert_to_findings
    convert_sarif(app_name, repo_context, sarif_files, findings_fname)
  File "/usr/local/src/lib/inspect.py", line 479, in convert_sarif
    with open(findings_fname, mode="w") as out_file:
PermissionError: [Errno 13] Permission denied: '/app/reports/ngsast-report.findings.json'

**Comment by prabhu** [comment]
Is this build step being run as root? The error message is due to the host machine preventing the folder creation for the current user. See if you can create the reports folder upfront and do a `chown`.

We have users who are able to run this as normal users so we should be able to get it working.

**Comment by prabhu** [comment]
```PermissionError: [Errno 13] Permission denied: '/.local'```

To resolve this particular error set the environment variable VDB_HOME to a directory that can be written to by scan.

**Comment by niltongouveajr** [comment]
Thank you. What about this?

`PermissionError: [Errno 13] Permission denied: '/app/reports/depscan-report-nodejs.json'`
`PermissionError: [Errno 13] Permission denied: '/app/reports/ngsast-report.findings.json'`

**Comment by niltongouveajr** [comment]
This fix the problem. Thank you very much!

**Comment by prabhu** [comment]
Thank you. Will you be able to kindly send a PR on scan-docs to update our docs?

https://github.com/ShiftLeftSecurity/scan-docs/blob/master/docs/integrations/jenkins.md

**Comment by niltongouveajr** [comment]
Sure @prabhu . I tested it first on Azure DevOps. I will test at Jenkins too. I can send a PR for both documents. How should I proceed? Should I create a new branch, push and create the a new PR? Can I do this in this private repository?
