### ISSUE TITLE
Python credscan false-positive CWE-312

### ISSUE THREAD

**Issue by BakanovKirill** [ShiftLeftSecurity/sast-scan#281]
Issue appeared with the change of the code from

```
redis_password = REDIS_CONNECTIONS['default']['password']
redis_host = REDIS_CONNECTIONS['default']['host']
redis_port = REDIS_CONNECTIONS['default']['port']

BROKER_URL = local_config.BROKER_URL.format(redis_password=redis_password, redis_port=redis_port)
```

to the next:

```
redis_password = REDIS_CONNECTIONS['default']['password']
redis_host = REDIS_CONNECTIONS['default']['host']
redis_port = REDIS_CONNECTIONS['default']['port']
# 'redis://:{redis_password}@example.com:{redis_port}/0'
BROKER_URL = local_config.BROKER_URL.format(
    redis_host=redis_host,
    redis_password=redis_password,
    redis_port=redis_port
)
```

And got CWE-312. And i have no idea how to avoid it. Is it a bug?

<img width="729" alt="Screenshot 2021-02-26 at 3 56 09 PM" src="https://user-images.githubusercontent.com/1275854/109308775-26934c80-784b-11eb-91cd-785c009e374c.png">

**Comment by BakanovKirill** [comment]
Looks like an error with `format()`, as it is only replacing the values in a string, not assigning passwords.

**Comment by prabhu** [comment]
Are you able to use the baseline feature to suppress this?

https://slscan.io/en/latest/getting-started/#baseline

redis_password is a known default password so do not want to suppress this in the default configuration.

**Comment by BakanovKirill** [comment]
@prabhu yes, thanks, just copied the basefile from the report and now this error is ignored
