### ISSUE TITLE
Possible cdxgen false-positives

### ISSUE THREAD

**Issue by erichs** [ShiftLeftSecurity/sast-scan#291]
I'm seeing false-positive BOM entries (and subsequent vuln findings) for NodeJS lodash@4.17.11 and 4.17.12, that don't seem to be present when running `cdxgen` version 2.2.19. Can the version of `cdxgen` be updated? Is there a way to locally configure the cdxgen version via `.sastscanrc`?

**Comment by prabhu** [comment]
Hi @erichs ,

scan image is built every day so should always have the latest cdxgen. scan invokes cdxgen in recurse mode with `-r`. Is it possible there are more than 1 package-lock.json or yarn.lock with multiple lodash versions?

**Comment by erichs** [comment]
ah, I see! Thanks @prabhu. Indeed, I can repro these findings with `cdxgen -r`.

**Comment by erichs** [comment]
Actually, I think there is still an issue. `cdxgen` BOM reporting appears to generate false-positives when privately scoped repositories in the public NPM registry are added as dependencies. I've isolated this, and attempted to document my findings here: https://github.com/erichs/testdependency-resolution

**Comment by erichs** [comment]
I think that perhaps `cdxgen` should ignore lockfiles whose full path contains `node_modules`. This will cover over the monorepo use-case while still respecting the resolutions of the top-level lockfiles (which should be considered the source of truth for BOM purposes).

**Comment by erichs** [comment]
Fixed as of v2.0.1.
