### ISSUE TITLE
Consider allowing users to bring their own CycloneDX SBOM files

### ISSUE THREAD

**Issue by erichs** [ShiftLeftSecurity/sast-scan#307]
There are a couple of cases where this can be helpful:

1. for whatever reason, a CycloneDX-compatible BOM file is already being generated with [one of these tools](https://cyclonedx.org/tool-center/)
2. the [underlying cdxgen](https://github.com/AppThreat/cdxgen/) cannot be made to work with the repo at hand

It would be really great to pass a path to a BOM.xml or BOM.json file via args or `.sastscanrc`, and have it skip the `bomgen` step for that run.

**Comment by erichs** [comment]
When cdxgen throws, only an `empty-scan-report.sarif` file is generated.

**Comment by prabhu** [comment]
@erichs This is an interesting idea. dep-scan already supports scanning based on an existing bom file - https://github.com/AppThreat/dep-scan/blob/master/depscan/cli.py#L95

So a .sastscanrc file like below would work assuming a bom.json exists in src directory.

{
  "depscan": [
        get("DEPSCAN_CMD"),
        "--no-banner",
        "--suggest",
        "--src",
        "%(src)s",
       "--bom",
        "%(src)s/bom.json",
        "--report_file",
        "%(report_fname_prefix)s.json"
    ]
}

**Comment by erichs** [comment]
Wow, I missed that. Perfect. Thanks also for the `.sastscanrc` example!
