### ISSUE TITLE
Latest Version Failing from docker run command

### ISSUE THREAD

**Issue by jrg-sierra** [ShiftLeftSecurity/sast-scan#363]
I was trying to use latest version (v2.0.4) in an azure devops pipeline, however, i got this error:

![image](https://user-images.githubusercontent.com/101296456/160145982-ac70045c-d9dd-4e00-a9f8-1cf3dee61e67.png)

I got it resolved by downgrading version to v2.0.3. Could you please check on this error message?

Thanks.

**Comment by aroysbox** [comment]
Yes similar error from yesterday in our environment as well

**Comment by hyeongguen-song** [comment]
https://github.com/ShiftLeftSecurity/scan-action/issues/30
Same as this
Is there any plan to fix?

**Comment by aviisingh** [comment]
It's same for me as well. Looks like some fix went in for Jinja.
https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2
When we can expect a fix for this?

**Comment by prabhu** [comment]
This issue is resolved now. Apologies.
