### ISSUE TITLE
SAST analyser for Type/JavaScript

### ISSUE THREAD

**Issue by daniel-ac-martin** [ShiftLeftSecurity/sast-scan#367]
I notice that [njsscan was previously included](https://github.com/ShiftLeftSecurity/sast-scan/issues/109).

Are there any clear plans on replacing this functionality? e.g. With NG SAST.

**Comment by prabhu** [comment]
@daniel-ac-martin Entire sast-scan project is now deprecated. We are working on adding javascript support for joern which is a proper data-flow analysis tool.

https://joern.io/

**Comment by daniel-ac-martin** [comment]
@prabhu: Ah I missed that. It's a shame as it looks like a great project. Thanks for letting me know.
