### ISSUE TITLE
Inconsistencies in flag names for src and out_dir

### ISSUE THREAD

**Issue by takirala** [ShiftLeftSecurity/sast-scan#37]
When i do a `scan -h` : 

```

Wrapper for various static analysis tools

optional arguments:
  -h, --help            show this help message and exit
  --src SRC_DIR         Source directory
  --out_dir REPORTS_DIR
                        Reports directory
  --type SCAN_TYPE      Override project type if auto-detection is incorrect.
                        Comma separated values for multiple types. Eg:
                        python,bash,credscan
  --convert             Convert results to sarif json format
  --no-error            Continue on error to prevent build from breaking
  --local-only          Do not enable cloud based scanning even for inspect
                        users
  --mode SCAN_MODE      Scan mode to use ci, ide, pr, release, deploy
```

Note that while most flags are using `-`, only `out_dir` flag is using `_`. Also the `src` (which needs to be a directory doesn't have a `dir` suffix while the `out_dir` has the `dir` suffix.

This is a silly UX issue but still noticeable when setting up as a beginner.

**Comment by prabhu** [comment]
I think this is a good observation. I kept `--src` generic so that we can support repo url and other sources in the future. The `--out_dir` flag was due to a side effect - to be compatible with a predecessor of scan which was used in some enterprises.

**Comment by prabhu** [comment]
I have now added `-i` and `-o` alias for these two parameters. Let me know what you think?

**Comment by takirala** [comment]
Sounds good @prabhu  :+1:

**Comment by prabhu** [comment]
Thank you. Marking this as closed.
