### ISSUE TITLE
Difference between "scan" and "sast-scan" docker images

### ISSUE THREAD

**Issue by sprathod369** [ShiftLeftSecurity/sast-scan#371]
Hi,
I happen to explore this tool and found it pretty useful and intersting. 
One quick question I had regarding the 2 docker images I see "san" and "sast-scan"
1) shiftleft/scan
2) shiftleft/sast-scan

I did not find anything different browsing through  the image layers in hub.docker.com. However when I ran the analysis using "scan" image and the "sast-scan" image against the same code repository, same branch I got a slightly different result showing severity summary for dependency Scan. What am I missing here ? Any inputs / clarifications will help.

using **shiftleft/scan** image
![image](https://user-images.githubusercontent.com/73107830/180404977-ffb91a21-2dc4-48ce-8b33-bd9c51a2dd58.png)

using **shiftleft/sast-scan** image
![image](https://user-images.githubusercontent.com/73107830/180404802-eff33ccf-5521-4346-86c9-3f3c49295161.png)

Thanks

**Comment by prabhu** [comment]
@sprathod369 Thank you for raising this issue. Ideally, the two images must be identical, but it looks like the build has started failing, so the images could be different.

https://dev.azure.com/shiftleftsecurity/sl-appthreat/_build?definitionId=11

You can set the environment variable SCAN_DEBUG_MODE=debug to see the underlying errors. I'm suspecting they are packaging different version of [dep-scan](https://github.com/AppThreat/dep-scan)

**Comment by sprathod369** [comment]
Thanks you @prabhu - appreciate your inputs. I did try to set the environment variable SCAN_DEBUG_MODE=debug but did not find anything highlighting the version of dep-scan (or versions of the scan tool tself or any of the integrated tool versions in use e.g checkov etc). This may possibly be an underlying error with "sast-scan" image 
![image](https://user-images.githubusercontent.com/73107830/180765547-7265025d-8e08-4ee4-8e2e-544346434239.png)

For now, it seems the "scan" image may be better off Vs the "sast-scan" image for now. Thanks again!!

**Comment by prabhu** [comment]
@sprathod369 This looks like a bug in https://github.com/AppThreat/vulnerability-db/. Could you help me by trying to replicate it there and file a bug in that repo with your observation?

**Comment by prabhu** [comment]
@sprathod369 are you still seeing this issue?

**Comment by sprathod369** [comment]
No longer an issue when I last checked a couple of weeks back.
