### ISSUE TITLE
DNS Resolution error for slscan.io

### ISSUE THREAD

**Issue by GridexX** [ShiftLeftSecurity/sast-scan#379]
### Current behavior

When requesting the site [slscan.io](http://slscan.io/), there is a Cloudflarre Error page that shows a DNS resolution error

![image](https://user-images.githubusercontent.com/50552672/215759629-4243a42a-c1ec-4862-95b0-fefde27cfb1d.png)

### Expected

The server hosting the website is probably done and should be restarted

**Comment by prabhu** [comment]
Please use appthreat.io[appthreat.io](appthreat.io)

**Comment by prabhu** [comment]
All links must point to the new corrected domain now.
