### ISSUE TITLE
Scan always finish with exit code 1

### ISSUE THREAD

**Issue by guidorapisarda** [ShiftLeftSecurity/sast-scan#384]
I'm using the `docker run --rm -e "WORKSPACE=${PWD}" -v $PWD:/app shiftleft/sast-scan scan` command to execute scans on my repo (it has python and terraform code). The exit code is always 1 (error) and no log is printed on the console.
![Error](https://user-images.githubusercontent.com/12972491/221696006-0d443c10-c727-4ce1-8541-96c5d9bb43e6.jpg)

I tried removing all the types of scan one by one, just to find that whatever scan type I'm using, it always ends with exit code 1. Can i enable some log tracing?

**Comment by prabhu** [comment]
@guidorapisarda automatic build breaker is a feature and is based on critical and high vulnerabilities found. You can pass the argument --no-error to disable this

**Comment by guidorapisarda** [comment]
Okey, thanks for the info and for your very fast response. I couldn't find that option on my own 🤣

**Comment by prabhu** [comment]
Not an issue. Happy to help!
