### ISSUE TITLE
Question: Any plans on supporting TypeScript and JavaScript?

### ISSUE THREAD

**Issue by awentzel** [ShiftLeftSecurity/sast-scan#52]
Thx

**Comment by conikeec** [comment]
@awentzel  happy to discuss JavaScript and TypeScript with you. We just launched the offering with our Inspect skew (https://www.shiftleft.io/inspect/).
Feel free to email me at  chetan@shiftleft.io to discuss further

**Comment by prabhu** [comment]
Thanks @conikeec 

To answer @awentzel specifically about OSS, scan uses nodejsscan which supports Node.js and JavaScript. The tool, however, is a little basic using mainly regex to detect vulnerabilities. I agree that JavaScript and TypeScript community would benefit from better tools but there is not much available on the OSS right now.

If you are aware of any such tool please let us know and I will be happy to review and integrate with scan.

**Comment by awentzel** [comment]
@conikeec @prabhu do you know what CodeQL Analysis uses?  I gave up on it already due to almost no documentation and it doesn't seem to work, but, curious.  I'll email.  It would be great to lead on the security front in our project https://github.com/microsoft/fast-dna.  We're leading on Web Components right now working across browser vendors.  I'll email to learn more about Inspect.  

ShiftLeft has done a great job on this front.

Thanks.

**Comment by conikeec** [comment]
@awentzel Would be great to take this conversation to email so that we can help you with clear next steps. I sent few emails over the past few weeks (from chetan@shiftleft.io) but haven't received a reply as yet. 
Let me know if you received the emails I sent.

**Comment by awentzel** [comment]
Feel free to close this issue, and we'll continue online early June to restart this convo.
