### ISSUE TITLE
When credscan scans, it prompts error: repository does not exist?

### ISSUE THREAD

**Issue by niuzhi** [ShiftLeftSecurity/sast-scan#84]
![image](https://user-images.githubusercontent.com/33443724/84341653-393ef600-abd6-11ea-845d-86caa284abe7.png)
can you help me?thanks

**Comment by prabhu** [comment]
@niuzhi credscan requires a git repository along with .git directory to work. Can you confirm how the repository was cloned and whether .git directory is present?

**Comment by niuzhi** [comment]
@prabhu thanks,I have solved it.
